"""empty message

Revision ID: 4801588ac094
Revises: 43a64519b88f
Create Date: 2020-10-19 23:37:23.389477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4801588ac094'
down_revision = '43a64519b88f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'artist_image_link')
    op.drop_column('shows', 'venue_name')
    op.drop_column('shows', 'artist_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('artist_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('shows', sa.Column('venue_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('shows', sa.Column('artist_image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
