"""empty message

Revision ID: 85ed03a2a760
Revises: be84f4e3e6be
Create Date: 2020-10-21 18:06:50.911733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ed03a2a760'
down_revision = 'be84f4e3e6be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venue_image_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'venue_image_link')
    # ### end Alembic commands ###
