"""empty message

Revision ID: 866eb13caaa8
Revises: 6fbc18fa4a9c
Create Date: 2020-10-19 02:04:39.936705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866eb13caaa8'
down_revision = '6fbc18fa4a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('website1', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'website1')
    # ### end Alembic commands ###
