"""empty message

Revision ID: c3d72ae61b1a
Revises: 4801588ac094
Create Date: 2020-10-20 00:42:22.008607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d72ae61b1a'
down_revision = '4801588ac094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_venue1', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'seeking_venue1')
    # ### end Alembic commands ###
