"""empty message

Revision ID: d6b863cbccad
Revises: c3d72ae61b1a
Create Date: 2020-10-21 15:40:54.737706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6b863cbccad'
down_revision = 'c3d72ae61b1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'seeking_venue1')
    op.drop_column('artists', 'seeking_venue')
    op.drop_column('venues', 'seeking_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('artists', sa.Column('seeking_venue', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('artists', sa.Column('seeking_venue1', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
